### PR TITLE
fix WpfDemo: image not displayed

### PR DESCRIPTION
**Pull request by pinkli**
1. fix WpfDemo: image not displayed;
2. upgrade console app to .Net 5

### CODE REVIEW

**Comment by GihanSoft** [comment]
@pinkli Tanks. I just merged your PR to my own fork 😅.

**Comment by pinkli** [comment]
@GihanSoft you're welcome.

**Comment by vers-one** [comment]
Sorry for a delayed response. Could you post a link to a EPUB file that reproduces this issue (assuming it's not under copyright restrictions)?

**Comment by pinkli** [comment]
https://molaware.oss-cn-beijing.aliyuncs.com/photographer-book-test.epub  see this epub, images will not show in html content pages.

**Comment by vers-one** [comment]
Thank you for providing a sample EPUB file. The change in the `GetFullPath` method looks good to me. If you extract it into a separate pull request, I will merge it right away.

As for the change in the `OnStylesheetLoad` method — I couldn't reproduce it with any of the EPUB files I have. All `font-family` CSS properties are handled properly for all the files I tested. Do you have a sample EPUB file that causes `HtmlRenderer` to throw an exception for a `font-family` property?

Still looking into the schema parsing changes.

**Comment by vers-one** [comment]
I will close and reopen this pull request to restart the build check.

**Comment by vers-one** [comment]
`GetFullPath` change was implemented in https://github.com/vers-one/EpubReader/commit/147c69063e5f096cc18120c740a3243a3756543e and the EPUB 3 cover support was added in this PR https://github.com/vers-one/EpubReader/pull/49.

Thank you for your contribution!

**Pull request closed without merging**
